name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./src
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Type Check
        run: pnpm check-type
  build:
    needs: type-check
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js from Type Check
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Build
        run: pnpm build
